// <auto-generated />
using System;
using GestionInformacion.Infraestructura.Datos.Persistencia.Core.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionInformacion.Infraestructura.Datos.Persistencia.Core.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20210325053624_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DominioGI.Administracion.Documento.DocumentTypeEntity", b =>
                {
                    b.Property<Guid>("KindOfIdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("IdentificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KindOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SignUpDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("KindOfIdentificationId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("DominioGI.Administracion.Personas.EmployeeEntity", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AreaOfWorkAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DocumentIDKindOfIdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("KindOfPerson")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SignUpDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AreaOfWorkAreaId");

                    b.HasIndex("DocumentIDKindOfIdentificationId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DominioGI.Administracion.Personas.ProviderEntity", b =>
                {
                    b.Property<Guid>("IdProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContactNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("KindOfIdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KindOfPerson")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProviderIdKindOfIdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SignUpDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IdProvider");

                    b.HasIndex("ProviderIdKindOfIdentificationId");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("DominioGI.Administration.Person.ClientEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DocumentIdKindOfIdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KindOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SignUpDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ClientId");

                    b.HasIndex("DocumentIdKindOfIdentificationId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("DominioGI.Areas.AreaEntity", b =>
                {
                    b.Property<Guid>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("KindOfPerson")
                        .HasColumnType("int");

                    b.Property<Guid>("ResponsableEmployedId")
                        .HasMaxLength(30)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SignUpDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AreaId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("DominioGI.Administracion.Personas.EmployeeEntity", b =>
                {
                    b.HasOne("DominioGI.Areas.AreaEntity", "AreaOfWork")
                        .WithMany("AreaEmployees")
                        .HasForeignKey("AreaOfWorkAreaId");

                    b.HasOne("DominioGI.Administracion.Documento.DocumentTypeEntity", "DocumentID")
                        .WithMany("EmployeesList")
                        .HasForeignKey("DocumentIDKindOfIdentificationId");

                    b.Navigation("AreaOfWork");

                    b.Navigation("DocumentID");
                });

            modelBuilder.Entity("DominioGI.Administracion.Personas.ProviderEntity", b =>
                {
                    b.HasOne("DominioGI.Administracion.Documento.DocumentTypeEntity", "ProviderId")
                        .WithMany("ProvidersList")
                        .HasForeignKey("ProviderIdKindOfIdentificationId");

                    b.Navigation("ProviderId");
                });

            modelBuilder.Entity("DominioGI.Administration.Person.ClientEntity", b =>
                {
                    b.HasOne("DominioGI.Administracion.Documento.DocumentTypeEntity", "DocumentId")
                        .WithMany("ClientsList")
                        .HasForeignKey("DocumentIdKindOfIdentificationId");

                    b.Navigation("DocumentId");
                });

            modelBuilder.Entity("DominioGI.Administracion.Documento.DocumentTypeEntity", b =>
                {
                    b.Navigation("ClientsList");

                    b.Navigation("EmployeesList");

                    b.Navigation("ProvidersList");
                });

            modelBuilder.Entity("DominioGI.Areas.AreaEntity", b =>
                {
                    b.Navigation("AreaEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
